const mongoose = require("mongoose");

const propertySchema = new mongoose.Schema(
  {
    title: { type: String, required: true, trim: true },
    description: { type: String, required: true, trim: true },
    price: { type: Number, required: true, min: 0 },
    propertyType: {
      type: String,
      enum: [
        "Apartment",
        "Villa",
        "Flat",
        "Individual House",
        "Rent",
        "PG",
        "Independent House",
        "Plot",
        "Commercial",
        "Commercial Land",
        "Commercial Land & Building",
        "Commercial Land / Building",
        "Agricultural Land",
        "Agri Land",
        "Farmland",
        "House",
        "Office",
        "Warehouse",
        "Empty Land",
        "Land",
        "Industrial Shed",
      ],
      required: true,
    },
    furnishingStatus: {
      type: String,
      enum: ["Furnished", "Semi-Furnished", "Unfurnished"],
      default: "Unfurnished",
    },
    bhk: { type: Number, min: 0 },
    bathrooms: { type: Number, min: 0, default: 1 },
    carpetArea: { type: Number, min: 0 },
    builtupArea: { type: Number, min: 0 },
    areaUnit: { type: String, enum: ["sqft", "sqm"], default: "sqft" },
    propertyClass: { type: String, trim: true, default: "General" },
    measurementType: { type: String, enum: ["Square Feet", "Cent", "Acre"], default: "Square Feet" },
    ratePerUnit: { type: Number, min: 0 },
    landArea: { type: String, trim: true },
    totalAmount: { type: Number, min: 0 },
    plotType: { type: String, trim: true },
    villaType: { type: String, trim: true },
    pgType: { type: String, trim: true },
    sharingType: { type: String, trim: true },
    monthlyMaintenance: { type: Number, min: 0 },
    maintenanceType: { type: String, trim: true },
    monthlyRent: { type: Number, min: 0 },
    advance: { type: String, trim: true },
    waterSourceType: { type: String, trim: true },
    waterSource: { type: String, trim: true },
    frontage: { type: String, trim: true },
    roadWidth: { type: String, trim: true },
    roadType: { type: String, trim: true },
    corner: { type: String, trim: true },
    farmhouseCount: { type: Number, min: 0 },
    soilType: { type: String, trim: true },
    cropSuitable: { type: String, trim: true },
    carParking: { type: String, trim: true },
    layoutPlot: { type: String, trim: true },
    individualPlot: { type: String, trim: true },
    floorNumber: { type: Number, min: 0 },
    totalFloors: { type: Number, min: 0 },
    possessionStatus: {
      type: String,
      enum: ["Ready to Move", "Under Construction"],
      default: "Ready to Move",
    },
    possessionDate: Date,
    facing: {
      type: String,
      enum: [
        "North",
        "South",
        "East",
        "West",
        "East North",
        "South West",
        "North-East",
        "North-West",
        "South-East",
        "South-West",
        "North East",
        "North West",
        "South East",
      ],
    },
    verification: {
      isVerified: { type: Boolean, default: false },
      reraId: { type: String, trim: true },
      lastVerifiedAt: Date,
    },
    location: {
      country: { type: String, required: true, trim: true, default: "India" },
      state: { type: String, required: true, trim: true },
      district: { type: String, required: true, trim: true },
      taluk: { type: String, required: true, trim: true },
      village: { type: String, required: true, trim: true },
      city: { type: String, required: true, trim: true },
      area: { type: String, required: true, trim: true },
      address: { type: String, trim: true },
      lat: Number,
      lng: Number,
    },
    amenities: [{ type: String }],
    nearbyFacilities: [{ type: String }],
    virtualTourUrl: { type: String, trim: true },
    warehouseDetails: { type: mongoose.Schema.Types.Mixed, default: undefined },
    listingContact: {
      name: { type: String, trim: true },
      phone: { type: String, trim: true },
      email: { type: String, trim: true, lowercase: true },
    },
    localityInsights: {
      rating: { type: Number, default: 4.1 },
      connectivity: { type: Number, default: 4.0 },
      safety: { type: Number, default: 3.9 },
      livability: { type: Number, default: 4.2 },
      notes: { type: String, default: "Good access to schools, transit, and daily essentials." },
    },
    images: [{ type: String }],
    documents: [{ type: String }],
    ownerId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    ownerType: { type: String, enum: ["seller", "agent", "broker", "builder"], required: true },
    status: { type: String, enum: ["pending", "approved", "rejected"], default: "pending" },
    listingType: { type: String, enum: ["sale", "rent", "new-project"], default: "sale" },
    listingSource: { type: String, enum: ["owner", "builder", "agent"], default: "owner" },
    isSold: { type: Boolean, default: false },
    soldAt: Date,
    expiresAt: Date,
    featuredUntil: Date,
    promotionalScore: { type: Number, default: 0 },
    viewCount: { type: Number, default: 0 },
    inquiryCount: { type: Number, default: 0 },
  },
  { timestamps: true }
);

propertySchema.index({
  "location.country": "text",
  "location.state": "text",
  "location.district": "text",
  "location.taluk": "text",
  "location.village": "text",
  "location.city": "text",
  "location.area": "text",
  title: "text",
});

module.exports = mongoose.model("Property", propertySchema);
