export const bankLoans = [
  {
    id: 1,
    name: "State Bank of India (SBI)",
    shortName: "SBI",
    minRate: 7.3,
    maxRate: 8.5,
    logo: "🏦",
    color: "from-sky-700 to-blue-500",
    description: "Government Bank",
    processingFee: "0.5% - 1%",
    maxLoanAmount: "1 Crore",
    minLoanAmount: "2 Lakhs",
    minTenure: "60 months",
    maxTenure: "360 months",
    features: [
      "Trusted public sector lender",
      "Wide branch network support",
      "Flexible repayment tenure",
      "Convenient online application process",
      "Suitable for salaried and self-employed borrowers",
    ],
    eligibility: [
      "Age: 21-70 years",
      "Annual income: ₹3 Lakhs minimum",
      "Credit score: 700+",
      "Stable income and repayment profile",
    ],
  },
  {
    id: 2,
    name: "Panjab National Bank (PNB)",
    shortName: "PNB",
    minRate: 7.3,
    maxRate: 7.8,
    logo: "🏦",
    color: "from-blue-600 to-blue-400",
    description: "Private Bank",
    processingFee: "0.5% - 1%",
    maxLoanAmount: "50 Lakhs",
    minLoanAmount: "2 Lakhs",
    minTenure: "60 months",
    maxTenure: "360 months",
    features: [
      "Competitive interest rates",
      "Flexible tenure options",
      "No prepayment penalty",
      "Online loan application",
      "Fast disbursement",
    ],
    eligibility: [
      "Age: 21-65 years",
      "Annual income: ₹3 Lakhs minimum",
      "Credit score: 700+",
      "Stable employment history",
    ],
  },
  {
    id: 3,
    name: "HDFC Bank",
    shortName: "HDFC",
    minRate: 7.3,
    maxRate: 7.8,
    logo: "🏦",
    color: "from-red-600 to-red-400",
    description: "Private Bank",
    processingFee: "0.5% - 1%",
    maxLoanAmount: "1 Crore",
    minLoanAmount: "2 Lakhs",
    minTenure: "60 months",
    maxTenure: "360 months",
    features: [
      "Premium customer benefits",
      "Attractive cashback offers",
      "Insurance coverage included",
      "Quick loan approval",
      "Expert financial counseling",
    ],
    eligibility: [
      "Age: 23-65 years",
      "Annual income: ₹2.5 Lakhs minimum",
      "Credit score: 700+",
      "Existing customer preferred",
    ],
  },
  {
    id: 4,
    name: "LIC Housing Finance",
    shortName: "LIC",
    minRate: 7.3,
    maxRate: 7.8,
    logo: "🏢",
    color: "from-orange-600 to-orange-400",
    description: "Government Bank",
    processingFee: "0.5% - 1.5%",
    maxLoanAmount: "50 Lakhs",
    minLoanAmount: "2 Lakhs",
    minTenure: "60 months",
    maxTenure: "300 months",
    features: [
      "Specialized housing finance",
      "Flexible payment options",
      "Personal accident insurance",
      "LIC policy benefits",
      "Extended tenure options",
    ],
    eligibility: [
      "Age: 21-70 years",
      "Annual income: ₹2 Lakhs minimum",
      "Credit score: 650+",
      "Self-employed and salaried applicants eligible",
    ],
  },
  {
    id: 5,
    name: "IDBI Bank",
    shortName: "IDBI",
    minRate: 6.7,
    maxRate: 7.5,
    logo: "🏦",
    color: "from-green-600 to-green-400",
    description: "Government Bank",
    processingFee: "0.5% - 1%",
    maxLoanAmount: "40 Lakhs",
    minLoanAmount: "2 Lakhs",
    minTenure: "60 months",
    maxTenure: "360 months",
    features: [
      "Best rates for salaried class",
      "Simple documentation",
      "No hidden charges",
      "Quick processing support",
      "Lifetime assistance",
    ],
    eligibility: [
      "Age: 21-60 years",
      "Annual income: ₹2.5 Lakhs minimum",
      "Credit score: 700+",
      "Salaried and self-employed applicants accepted",
    ],
  },
  {
    id: 6,
    name: "Can Fin Homes Ltd",
    shortName: "Can Fin",
    minRate: 7.8,
    maxRate: 12,
    logo: "🏠",
    color: "from-violet-600 to-fuchsia-400",
    description: "Private Bank",
    processingFee: "0.5% - 1.5%",
    maxLoanAmount: "75 Lakhs",
    minLoanAmount: "2 Lakhs",
    minTenure: "60 months",
    maxTenure: "360 months",
    features: [
      "Focused housing finance solutions",
      "Flexible repayment structures",
      "Support for salaried and self-employed customers",
      "Simple documentation flow",
      "Fast eligibility review",
    ],
    eligibility: [
      "Age: 21-70 years",
      "Annual income: ₹2.5 Lakhs minimum",
      "Credit score: 680+",
      "Income stability required",
    ],
  },
  {
    id: 7,
    name: "Aditya Birla Capital",
    shortName: "Aditya Birla",
    minRate: 7.8,
    maxRate: 12,
    logo: "🏛️",
    color: "from-rose-600 to-pink-400",
    description: "Private Bank",
    processingFee: "0.5% - 1.5%",
    maxLoanAmount: "75 Lakhs",
    minLoanAmount: "2 Lakhs",
    minTenure: "60 months",
    maxTenure: "360 months",
    features: [
      "Flexible home loan options",
      "Balance transfer support",
      "Quick digital onboarding",
      "Structured customer assistance",
      "Repayment plans tailored to borrower profile",
    ],
    eligibility: [
      "Age: 21-65 years",
      "Annual income: ₹2.5 Lakhs minimum",
      "Credit score: 680+",
      "Salaried and self-employed applicants eligible",
    ],
  },
];

export const loanTenures = [
  { label: "5 years", value: 60 },
  { label: "10 years", value: 120 },
  { label: "15 years", value: 180 },
  { label: "20 years", value: 240 },
];
