export const PROPERTY_REQUEST_TYPES = [
  "Apartment",
  "Villa",
  "Independent House",
  "Plot",
  "Commercial",
  "House",
  "Office",
  "Warehouse",
  "Land",
  "Industrial Shed",
];

export const RENT_REQUEST_TYPES = ["House", "Office", "Commercial", "Warehouse", "Land", "Industrial Shed"];

export const BANK_OPTIONS = [
  "SBI (State Bank of India)",
  "HDFC Bank",
  "ICICI Bank",
  "Axis Bank",
  "Canara Bank",
  "Bank of Baroda",
  "LIC Housing Finance",
  "Indian Bank",
  "Union Bank of India",
  "IDFC FIRST Bank",
  "Other / Partner Bank",
];

export const SERVICE_REQUEST_OPTIONS = {
  property_buy: {
    label: "Buy Property",
    requestCategory: "property_buy",
    propertyTypes: PROPERTY_REQUEST_TYPES,
    serviceTypes: [
      "Find your property",
      "Property guidance for buy sell and rent",
      "Sale agreement support",
      "Legal verification support",
      "Patta transfer",
      "Land survey",
      "Sale deed registration",
    ],
    budgetLabel: "Budget",
    showBudget: true,
  },
  property_sell: {
    label: "Sell Property",
    requestCategory: "property_sell",
    propertyTypes: PROPERTY_REQUEST_TYPES,
    serviceTypes: [
      "Sell your property",
      "Property guidance for buy sell and rent",
    ],
    budgetLabel: "Expected Price",
    showBudget: true,
  },
  property_rent: {
    label: "Rent Property",
    requestCategory: "property_rent",
    propertyTypes: RENT_REQUEST_TYPES,
    serviceTypes: [
      "Rent your property",
      "Property guidance for buy sell and rent",
    ],
    budgetLabel: "Monthly Rent Budget",
    showBudget: true,
  },
  loan: {
    label: "Loan",
    requestCategory: "loan",
    serviceTypes: [
      "Home Loan",
      "Plot Loan",
      "Mortgage Loan",
      "Commercial Loan",
      "Agriculture Loan",
      "Home Loan Balance Transfer",
      "Private Finance",
    ],
    budgetLabel: "Loan Amount",
    showBankDropdown: true,
    showBudget: true,
  },
  interior: {
    label: "Interior",
    requestCategory: "interior",
    serviceTypes: ["Home Interior", "Office Interior"],
    budgetLabel: "Project Budget",
    showBudget: false,
  },
  construction: {
    label: "Construction",
    requestCategory: "construction",
    serviceTypes: [
      "House Construction",
      "Office Construction",
      "Commercial Building",
      "Apartment",
      "Industry & Warehouse",
      "Approval plans",
      "2D Plan",
      "3D Plan",
      "HNTDA Approval",
      "RERA Approval",
      "Building Plan & Approval",
    ],
    budgetLabel: "Project Budget",
    showBudget: true,
  },
  property_management: {
    label: "Property Management",
    requestCategory: "property_management",
    serviceTypes: [
      "Home & Apartment Facility AMC Service",
      "Industry & Warehouse Facility AMC Service",
      "Land Scaping & Garden Maintenance Property Management Service",
      "NRI Property Management Service",
      "Property Management Service",
    ],
    budgetLabel: "Annual Budget",
    showBudget: false,
  },
  home_office_services: {
    label: "Home & Office Services",
    requestCategory: "home_office_services",
    serviceTypes: [
      "Home & Office Cleaning Service - Deep Cleaning",
      "Home & Office Shifting Service - Packers & Movers",
      "Home Appliance Service - TV, Fridge, Washing Machine Service",
      "Electrical & Plumbing Service",
      "Interior & Carpentry Work",
      "Pest Control Service",
      "Tank, Sump & Bathroom Cleaning Service",
      "Painting Work",
      "Sofa & Carpet Cleaning",
    ],
    budgetLabel: "Service Budget",
    showBudget: false,
  },
};

export const SERVICE_REQUEST_CATEGORY_LIST = Object.values(SERVICE_REQUEST_OPTIONS);
