const plans = [
  // ── 1. FREE TIER FOR 1ST TIME USERS ──
  {
    name: "Free / 1st Time User",
    subtitle: "3 Free Postings for 1st Time Users",
    price: 0,
    billingLabel: "Free",
    ctaLabel: "Start Free",
    recommended: false,
    features: [
      "3 Free Property Postings for 1st time users",
      "Posts valid for 90 days",
      "1 Contact Request per day limit",
      "Standard Search Visibility",
    ],
    listingLimit: 3,
    durationDays: 90,
    featuredBoost: false,
    category: "seller_listing",
    targetRole: ["customer", "seller", "agent", "broker"],
    contactUnlocks: 30,
    leadCredits: 0,
    boostDays: 0,
  },

  // ── 2. AGENT / BROKER / SELLER PLANS ──
  {
    name: "Pro Agent Plan",
    subtitle: "Most Popular Choice for Agents",
    price: 2999,
    billingLabel: "/month",
    ctaLabel: "Choose Pro Plan",
    recommended: true,
    features: [
      "6 Active Property Listings",
      "25 Customer Contact Requests",
      "20 Verified Lead Credits",
      "Featured Property Highlights",
      "Priority Agent Support",
    ],
    listingLimit: 6,
    durationDays: 30,
    featuredBoost: true,
    category: "broker_leads",
    targetRole: ["agent", "broker", "builder", "seller"],
    contactUnlocks: 25,
    leadCredits: 20,
    boostDays: 10,
  },
  {
    name: "Premium Agent Plan",
    subtitle: "For established agencies & top brokers",
    price: 4999,
    billingLabel: "/month",
    ctaLabel: "Choose Premium Plan",
    recommended: false,
    features: [
      "12 Active Property Listings",
      "35 Customer Contact Requests",
      "30 Verified Lead Credits",
      "Top Search Placement & Priority Boost",
      "Dedicated Relationship Support",
    ],
    listingLimit: 12,
    durationDays: 30,
    featuredBoost: true,
    category: "broker_leads",
    targetRole: ["agent", "broker", "builder", "seller"],
    contactUnlocks: 35,
    leadCredits: 30,
    boostDays: 20,
  },

  // ── 3. DATABASE PACKAGES ──
  {
    name: "Database Pack: ₹2,500",
    subtitle: "Hosur Buyer & Investor Contacts Pack",
    price: 2500,
    billingLabel: "/package",
    ctaLabel: "Purchase Database Pack",
    recommended: false,
    features: [
      "Verified Hosur Buyer & Investor Contacts",
      "Direct Buyer Phone & Email Access",
      "Location & Budget Preference Data",
    ],
    listingLimit: 0,
    durationDays: 30,
    featuredBoost: false,
    category: "database_access",
    targetRole: ["all"],
    contactUnlocks: 50,
    leadCredits: 0,
    boostDays: 0,
  },
  {
    name: "Database Pack: ₹5,000",
    subtitle: "Complete Hosur Real Estate Contacts Pack",
    price: 5000,
    billingLabel: "/package",
    ctaLabel: "Purchase Database Pack",
    recommended: true,
    features: [
      "Complete Hosur Real Estate Contact Database",
      "Separate Buyer, Seller & Investor Lists",
      "Full Contact Info & Requirement Details",
      "Priority Updates & Direct Download Access",
    ],
    listingLimit: 0,
    durationDays: 30,
    featuredBoost: false,
    category: "database_access",
    targetRole: ["all"],
    contactUnlocks: 120,
    leadCredits: 0,
    boostDays: 0,
  },
];

module.exports = plans;
